### ISSUE TITLE
waveforms generators for injections

### ISSUE THREAD

**Issue by MariaAssiduo** [ligo-cbc/pycbc-config#75]
Hi, where can I find the full list and the definitions of the waveforms generators available?

For example in the code are specified like:

```
SpinTaylorT2threePointFivePN
SpinTaylorT4threePointFivePN
SEOBNRv4pseudoFourPN
IMRPhenomDpseudoFourPN
```

Thank you in advance.

**Comment by pannarale** [comment]
Hi Maria, `lal-siminspiral --help` gives you the list of available time-domain and frequency-domain approximants.  What do you mean when you say definitions?  The relevant bibliography?

**Comment by spxiwh** [comment]
See "what waveforms can I generate" here:

http://pycbc.org/pycbc/latest/html/waveform.html#what-waveforms-can-i-generate

In theory this would also include any waveforms available *outside* of lal, but there's very few of those right now.

... You don't need the "threePointFivePN or "pseudoFourPN" bits in PyCBC, but it won't hurt to have them.

**Comment by MariaAssiduo** [comment]
@pannarale @spxiwh Hi, thank you for answer.  I noticed that in` lalapps_inspinj` the names are speciefied differently. For example, I have to write `SpinTaylorT4threePointFivePN` and not simply `SpinTaylorT4`. Since I have to generate injections with the approximants `IMRPhenomPv2` and `IMRPhenomXPHM`, I was wondering if I need the _Generators_ names to specify so that `lalapps_inspinj` can recognize them. I didn't mean the bibliography!

**Comment by titodalcanton** [comment]
@MariaAssiduo I am closing this issue as it is not very relevant to this repository. To use `lalapps_inspinj` with `IMRPhenom` models, I would try appending `pseudoFourPN` to the name or the model. If that does not work, and you still need an answer, try asking the LVK waveform group on chat.ligo.org, or by email.
